defmodule SarthakAdmissionWeb.SecondaryView do
  use SarthakAdmissionWeb, :view

  def get_secondary_subjects() do
    [
      {"Choose Subject", ""},
      {"ADDITIONAL MATHAMETICS", "ADDLM"},
      {"ADDITIONAL ENGLISH", "ADENG"},
      {"ADVANCED MATHEMATICS", "ADVM"},
      {"ARTS", "ART"},
      {"BENGALI", "BENG"},
      {"BENGALI(A)", "BENG A"},
      {"BENGALI (B)", "BENG B"},
      {"BIOLOGY", "BIO"},
      {"BUSINESS MATHEMATICS", "BM"},
      {"CHEMISTRY", "CHM"},
      {"COMPUTER APPLICATION", "CMAP"},
      {"COMMERCE", "COM"},
      {"COMMERCIAL APPLICATION", "COMAP"},
      {"DRAWING", "DRW"},
      {"ENGLISH ASSAMESE", "EA"},
      {"ECONOMICS APPLICATIONS", "ECOA"},
      {"ADV. MATHS.", "ELECT MATH"},
      {"ENVIORMENTAL MANAGEMENT", "EM"},
      {"ENGLISH", "ENG"},
      {"ENGLISH (A)", "ENG (A)"},
      {"ENGLISH (B)", "ENG (B)"},
      {"ALTERNETIVE ENGLISH", "ENGALTR"},
      {"ENGLISH CORE", "ENGCOR"},
      {"ENVIRONMENTAL APPLICATION", "ENVAPL"},
      {"ENVIRONMENTAL EDUCATION", "EV"},
      {"ENVIORMENTAL SCIENCE", "EVS"},
      {"FASHION DESIGNING", "FADGN"},
      {"FOUNDATION OF IT", "FN. IT"},
      {"GEOGRAPHY", "GEO"},
      {"GEOLOGY", "GEOLGY"},
      {"GENERAL STUDIES", "GS"},
      {"HISTORY CIVICS GEOGRAPHY", "HCG"},
      {"HEALTH EDUCATION", "HE EDU"},
      {"HINDI", "HIN"},
      {"HINDI (A)", "HIN (A)"},
      {"HINDI (B)", "HIN (B)"},
      {"HINDI+E3NGLISH", "HINENG"},
      {"HINDI+URDU", "HINURD"},
      {"HISTORY", "HIS"},
      {"HISTORY CIVICS SCINCE GEOGRAPHY", "HISCIVSCGEO"},
      {"HOME SCIENCE", "HSC"},
      {"HISTORY &amp; GEOGRAPHY", "HSGO"},
      {"INFORMATION &amp; COMMUNICATION TECHNOLOGY", "ICT"},
      {"INTRODUCTORY I T", "IIT"},
      {"LIFESCIENCE", "LSC"},
      {"MATHEMATICS", "MATH"},
      {"MECHANICS", "MECHN"},
      {"MAITHILI", "MIL"},
      {"MULTY MEDIA", "MLM"},
      {"MUSIC", "MUS"},
      {"BOOK KEEPING", "OES"},
      {"ORIA", "ORY"},
      {"PHYSICS,CHEMISTRY &amp; BIOLOGY", "PHCHBO"},
      {"PHY &amp; HEALTH EDUCATION", "PHE"},
      {"PHYSICAL SCIENCE", "PHS"},
      {"PHYSICS", "PHY"},
      {"POLSCIENCE", "POLSC"},
      {"PERSIAN", "PRS"},
      {"PISCICULTURE", "PSCL"},
      {"SANSKRIT", "SANS"},
      {"SCIENCE AND TECHNOLOGY", "SCANDTECH"},
      {"SCIENCE", "SCN"},
      {"SOCIAL SCIENCE", "SOCSC"},
      {"SOCIAL STUDIES", "SST"},
      {"SUPW", "SUPW"},
      {"TECHNICAL DRAWING APPLICATION", "TDA"},
      {"URDU", "UR"},
      {"URDU A", "URD (A)"},
      {"URDU B", "URD (B)"},
      {"WORK EDUCATION", "WE"},
      {"WORK EDUCATION PHISICAL EDUCATION", "WORKEPHE"}
    ]
  end
end
